site_name: Brendan Martin
site_author: Brendan Martin

theme: 
  name: material
  language: 'en'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  logo: images/staff_photo.jpg

nav: 
  - "Home": index.md 
  - "About": about.md 


extra: 
  social:
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/brendanmartin98" 

